### ISSUE TITLE
Default 3.0.16 -> Build Broken

### ISSUE THREAD

**Issue by sysvar** [akaunting/docker#101]
I'll start by saying version 3.0.15 is working for anyone wanting to get it working. Just change `docker-compose.yml` from: `docker.io/akaunting/akaunting:latest` to this: `docker.io/akaunting/akaunting:3.0.15`.

### Recreate issue
You bring the stack up for the first time using `AKAUNTING_SETUP=true docker compose up -d` after a few moments the following errors are seen which loop:

```Setting locale en-US
Creating database tables
Connecting to database akaunting@mariadb-akaunting:3306
Creating company
In CreateCompany.php line 61:

Not able to create a new user.

Setting locale en-US
Creating database tables
Connecting to database akaunting@mariadb-akaunting:3306
Creating company
In CreateCompany.php line 61:

Not able to create a new user.

**Comment by cevatkerim** [comment]
yeah this docker file is broken. It seems like it just downloads the latest and runs the same shell script. Check the Dockerfile

**Comment by cuneytsenturk** [comment]
Thank @sevannerse This issue solved.
