### ISSUE TITLE
Can not open web application in browser after running docker-compose without any error

### ISSUE THREAD

**Issue by krswin** [akaunting/docker#11]
Hello, 

Please help. I can not open web application in browser, i see docker-compose run fine and all 3 docker container running fine. 
I have tried to open 
http://localhost:8080/
http://localhost:8080/admin
http://localhost:8080/akaunting-directory

but i just get blank white page in response. 
Thank you for your time.

**Comment by ConorIA** [comment]
Try opening the developer tools in your browser and check the console for errors.

**Comment by krswin** [comment]
@ConorIA Thanks for reply. I found 403 Forbidden.

**Comment by Dubiy** [comment]
I have same problem

**Comment by jpfss** [comment]
the same problems,too
