### ISSUE TITLE
generating locales

### ISSUE THREAD

**Issue by karneaud** [akaunting/docker#12]
I'm using your image to run Akaunting locally but I would like to know....

is generating the locales necessary if you are english speaking only?

**Comment by stelgenhof** [comment]
Also agree with this. It should be possible to configure only the locales that you need.

**Comment by denisdulici** [comment]
Feel free to contribute #13

**Comment by stelgenhof** [comment]
@karneaud 

A quick hack could be the following. Replace this in the PHP Dockerfile to use only the en_US locale:
```
# RUN cp /usr/share/i18n/SUPPORTED /etc/locale.gen
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
```
