### ISSUE TITLE
Not Working Out of The Box

### ISSUE THREAD

**Issue by hatemjaber** [akaunting/docker#16]
First of all, thank you for contributing the time and effort to supply a product like of this maturity.

My issue with the docker-compose was resolved with a few changes, not sure what type of system you're testing on and how it's working on your end, but this is what I had to change to get it to work:

env/run.env
DB_HOST=akaunting-db

docker-compose.yml
```
... 
  akaunting:
    ports:
      - "8080:80"
     ...
    depends_on:
      - akaunting-db
...
  akaunting-db:
    ...
   ports:
    - "3306:3306"
```

The only way to get the containers to communicate between each other was to add the depends_on to the akaunting container in combination with changing the DB_HOST in the run.env. I also added 3306 to the db so I can view the content in MySQL Workbench. The quotes around the ports comes from a recommendation from Docker which I will link below.

https://docs.docker.com/compose/compose-file/

**Comment by solacelost** [comment]
Sorry - I don't have Docker. I thought you'd be able to hit the loopback IP like I can in rootless podman pod networking.

Good call on the `depends_on` to prevent Akaunting from missing the DB, though. Fixed :)

**Comment by solacelost** [comment]
Also, note on the quotes:

I'm aware of the limitations of YAML parsers, and if the ports were in danger of being interpreted as a timestamp they should be quoted. It's a style decision whether you should quote them all indiscriminately, and I don't believe that you should. Part of the beauty of YAML is its ability to remain remarkably close to a modest structure imposed on ordinary text. You should be aware of the limitations of the parser, and work around them when they rear their heads, but I don't believe you should treat perfectly parsable YAML that does what it's intended to do as if it were something to be held at arm's length. Strings are strings.

You're welcome to disagree, but I write a _lot_ of YAML and don't think it should be necessary.

> When mapping ports in the HOST:CONTAINER format, you may experience erroneous results **when using a container port lower than 60**, because YAML parses numbers in the format xx:yy as a base-60 value.

It's not like someone's going to change the destination port on the container and have it work, whether it's in quotes or not.

I wouldn't be mad if you PR'd to add the quotation marks, I just won't. :)
