### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by JamiePhonic** [akaunting/docker#18]
Howdy!

First off, this container works perfectly, however it took some fiddling to get it working...

The main issue is that `docker-compose up` does not appear have a -e parameter.
To start the stack with the AKAUNTING_SETUP arguement, it must be specified before the docker-compose command (or in the run.env file and later commented out):
`(sudo) AKAUNTING_SETUP=true docker-compose up -d`

This is true for docker-compose installed from repository on Ubuntu 20.04
![image](https://user-images.githubusercontent.com/4817698/107414604-246e8580-6b0a-11eb-894e-efb064725a08.png)

The current command specified in the readme causes docker-compose to display its help output:
![image](https://user-images.githubusercontent.com/4817698/107414568-1882c380-6b0a-11eb-8097-2147d5969937.png)

**Comment by solacelost** [comment]
Thanks for the heads up @JamiePhonic :+1:
