### ISSUE TITLE
Publish an official image on the docker hub / store?

### ISSUE THREAD

**Issue by ForsakenHarmony** [akaunting/docker#2]
Are there any plans to publish an image?

There are unofficial ones, but it would be preferable to have an automated build from you

**Comment by denisdulici** [comment]
For sure, an official image will be available on docker hub very soon.

**Comment by denisdulici** [comment]
Waiting for @hmert to make this available.

**Comment by denisdulici** [comment]
@hmert Any ETA for this?

**Comment by bd8392** [comment]
+1 for publication :-)

**Comment by bd8392** [comment]
Hi =9 I want to do a little contribution, and built a dockjerfile you can use for publishing :-) Is someone willing to test it with mariadb? =):

'''
FROM php:7.4-apache

RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libzip-dev \
    imagemagick \
    libmcrypt-dev \
    libpng-dev \
    libpq-dev \
    libxrender1 \
    locales \
    openssh-client \
    patch \
    unzip \
    zlib1g-dev \
    zip \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    gd \
    bcmath \
    pcntl \
    pdo \
    pdo_pgsql \
    pdo_mysql \
    zip

RUN docker-php-ext-configure gd --with-freetype --with-jpeg

RUN cp /usr/share/i18n/SUPPORTED /etc/locale.gen
RUN locale-gen

RUN wget -O akaunting.zip "https://akaunting.com/download.php?version=latest&utm_source=docker&utm_campaign=developers"
RUN mkdir -p /var/www/akaunting
RUN unzip akaunting.zip -d /var/www/akaunting
RUN rm akaunting.zip

RUN find /var/www/akaunting/ -type d -exec chmod 755 {} \;
RUN find /var/www/akaunting/ -type f -exec chmod 644 {} \;
'''

It's a simple combination with your two existing dockerfiles, into one for apache =) (It's easier and mor convenient =)). Let me know if this helps =)

**Comment by bd8392** [comment]
any news on this?

**Comment by denisdulici** [comment]
@bd8392 The maintainers of this repo have kinda vanished. I'd give you more access to the repo but your profile doesn't give confidence, sorry.

If anyone else is interested in maintaining the repo/image, feel free to reply.

**Comment by bd8392** [comment]
> @bd8392 The maintainers of this repo have kinda vanished. I'd give you more access to the repo but your profile doesn't give confidence, sorry.

Oh no I understand =). I've nerver maintained a repo before and have not tested akaunting yet because of the missing official docker...I will update my profile soon and maybe we can work together, but I would not dare to be the sole maintainer of this...I need at least an experienced akaunting user, and someone familiar with entrypoint scripts in docker (because I would establish an updating mechanism directly into docker like nextcloud does. It has prooven to be extremly liable, but is rather complicated to establish...)

**Comment by ForsakenHarmony** [comment]
Has this been closed because there's no maintainer or because there's an official image now?

**Comment by denisdulici** [comment]
Due to no maintainer.
