### ISSUE TITLE
ARM and ARM64 support?

### ISSUE THREAD

**Issue by armond1978** [akaunting/docker#21]
Great job on the recent efforts for publishing on Docker Hub! Is there any plan to publish docker images for ARM and ARM64 platforms (Raspberry Pi)? And if yes, is there any ETA?

Thanks!

**Comment by NajibNour** [comment]
@denisdulici Permission for me to upload an ARM version onto docker hub?

**Comment by MohammedAl-Mahdawi** [comment]
Hi!

We are testing the possibilities, probably soon you may find an official Akaunting ARM base image(s), so stay tuned!

**Comment by d9media** [comment]
any updates?
