### ISSUE TITLE
Diffrent DB Port not working

### ISSUE THREAD

**Issue by wuast94** [akaunting/docker#27]
When i add the DB_HOST variable with 192.168.178.26:3308 i get the following error on startup:

Connecting to database akaunting@192.168.178.26:3308:3306

so the port seems to be hardcoded anywhere ?

**Comment by MohammedAl-Mahdawi** [comment]
You must set `DB_HOST` and `DB_PORT` separately.

**Comment by wuast94** [comment]
DB_PORT has no effekt, still try to use port 3306 instead of 3308

**Comment by MohammedAl-Mahdawi** [comment]
Have you tried to change the values in the .env file?
Probably you have it hard coded in a .env file.

**Comment by wuast94** [comment]
i dont use a .env file. plain docker command

**Comment by MohammedAl-Mahdawi** [comment]
There will be a .env file inside the container unless you manually removed it.

**Comment by wuast94** [comment]
Where is it located? Then I can map it outside of the container to have a persist von if over updates :)

**Comment by MohammedAl-Mahdawi** [comment]
/var/www/html/.env

**Comment by wuast94** [comment]
i copied the .env file from https://akaunting.com/download.php?version=latest&utm_source=docker&utm_campaign=developers 
changed the port there and mapped the file to /var/www/html/.env .. still the same problem

**Comment by MohammedAl-Mahdawi** [comment]
I just found it hard coded in

**Comment by MohammedAl-Mahdawi** [comment]
I just tested it and everything seems to be normal, as you can see in config/database.php:

`'port' => env('DB_PORT', '3306'),`

So just change it in `/var/www/html/.env` and make sure you don't have for example environment variable that has a different value.

**Comment by a575606** [comment]
Doesn't work for me either.  As @wuast94 mentioned, setting the DB_PORT environment variable or mapping and modifying /var/www/html/.env DB_PORT has no effect. My database is accessible at port 3307, but no matter what I set DB_PORT to be, the app tries to connect to port 3306

**Comment by deployn** [comment]
So same problem. @a575606 did you manage to find a solution?
I mapped the .env file and can see it in the accounting container when executing it. But it is still connecting to database akaunting@akaunting-db:3306...
