### ISSUE TITLE
Akaunting login, not working on docker-compose either

### ISSUE THREAD

**Issue by 0ctatr0n** [akaunting/docker#28]
Using the vanilla docker-compose script of Akaunting on a centos 7 box;  Setup as per instructions and by filling out the run.env and db.env; ran the Akaunting_setup=true and while all the composing stuff whizzed by on the screen it stopped and told me "line 59 of Module.php call to a member function get() on null" had an issue;  tried a few times, no change; then started the containers normally and it asks me to restart apache2 service, did that and up comes the login screen; tried to login with details I put in run.env, nope incorrect; tried a few other things and it would just sit there acting like it's thinking about it but never goes anywhere, just like the person running it on the Synology NAS. 

I'd like to request a feature added where Akaunting command line can spit out the username and password on docker exec if this happens as I haven't setup the email service yet.

Thanks, Look forward to using this for my invoicing and importing my Wave transactions soon

**Comment by MohammedAl-Mahdawi** [comment]
I just tested it on CentOS 7 and it worked just fine, it is a setup-specific issue, please make sure everything correct with your setup.
