### ISSUE TITLE
Do these images work out the box?

### ISSUE THREAD

**Issue by EternalDeiwos** [akaunting/docker#30]
I've been fighting with these images for days now trying to get Akaunting deployed using docker. The closest I've gotten is using @solacelost's image which he links in #13. The problem there is I get errors when I try to install apps that don't appear in any logs or indicate what is causing them.

Just currently wondering if anyone is having success in using these images in any real capacity? and if so, then how?

**Comment by solacelost** [comment]
I should probably implement [this](https://github.com/akaunting/docker/commit/75bb60bfb74f61b0457d2f72176d66dec897ff70) for my images to fix that.

I'm unsure of the status of this repo. You're welcome to fork mine, or build from an older commit here possibly?

**Comment by MohammedAl-Mahdawi** [comment]
Yes, they are working, we never push an image unless we test it, please first make sure the image that you run contains what you want, for example not all images ships with composer, and second make sure your configuration is correct, for example, 
 have you enabled the logging in the configuration? and third, make sure what you are doing is possible with the image that you selected and you are doing it the right way.
