### ISSUE TITLE
login broken after initial setup 

### ISSUE THREAD

**Issue by joao-matos** [akaunting/docker#31]
Steps to reproduce the issue: follow the instruction on the readme.
after the down and up, default login (from the env file) doesn't work.

Log:
https://privatebin.at/?21f9947b2a7d3fd2#4htCsQqeZ9cRAEQ6Eotao2S2GEitJ3kYF4A8wiHdGDbX

**Comment by joao-matos** [comment]
da f*? why was this closed?
Unbelievable... the lack of respect is out of this world!

**Comment by MohammedAl-Mahdawi** [comment]
This issue has been closed due to a lack of information, we couldn't reproduce it with the standard setup.

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

This repo is for building the official Akaunting images so please only post issues related to the official Akaunting images or the default setup of the compose files.

If you have questions or issues with your specific setup you can post your question/issue in our support channels [here](https://akaunting.com/support) or on StackOverflow.

Thank you for understanding!
