### ISSUE TITLE
can't switch to Polish language

### ISSUE THREAD

**Issue by kamilkrzeminski** [akaunting/docker#32]
How can I enable Polish translation in self-hosted Docker deployment? Polish language is unavailable on the list, regardless it's in the main repository and should be already available.

**Comment by MohammedAl-Mahdawi** [comment]
I just tested it and it exists:

<img width="621" alt="Screen Shot 2021-05-28 at 9 18 08 AM" src="https://user-images.githubusercontent.com/5562839/119939832-177d8100-bf97-11eb-9ab6-c54e5cf8dbb0.png">

I can see the language is recently added to Akaunting please make sure you use the latest image.
