### ISSUE TITLE
REQUEST:

### ISSUE THREAD

**Issue by NajibNour** [akaunting/docker#33]
Could we get an explanation of what is stored within the different volumes? Are bills/invoice data found in the DB volume? Is company info found in the data volume? What is in the modules volume?

Thanks,
Najib.

**Comment by NajibNour** [comment]
Could we get an explanation of what is stored within the different volumes? Are bills/invoice data found in the DB volume? Is company info found in the data volume? What is in the modules volume?

Thanks,
Najib.

**Comment by MohammedAl-Mahdawi** [comment]
The database files stored in `akaunting-db` volume, the modules files stored in `akaunting-modules` volume,  and the storage files stored in `akaunting-data` volume.
