### ISSUE TITLE
All versions of docker images are pulling the latest version of Akaunting

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [akaunting/docker#35]
I am noticing the older versions of Docker images are all pulling the `latest` version of Akaunting.
![image](https://user-images.githubusercontent.com/13748882/116845310-1dd04580-ac03-11eb-812b-4a363f159eaa.png)

This will probably cause some unintended behaviour for people willing to stick to a particular patch version as restarting the container will fetch a different version of akaunting than the one they were running.

This might even cause bigger problems when Akaunting 2.2.x or 3.x is released.

I know the README recommends testing things in a dev environment but we are deploying in kubernetes and the kubermetes can restart a container for a variety of reasons and so it might cause problems.

I suggest that instead of downloading from `akaunting.com` one can download the versioned zip from `https://github.com/akaunting/akaunting/releases/download/2.1.11/Akaunting_2.1.11-Stable.zip`.

I can create a PR if needed.

**Comment by MohammedAl-Mahdawi** [comment]
Currently, we are using the rolling tags update mechanism, so let's take the current Akaunting release 2.1.14 and explain it:

- The latest tag always points to the latest revision of the Akaunting image.
- The 2 tag is a rolling tag that always points to the latest revision of Akaunting 2.x.
- The 2.1.14 tag is a rolling tag that points to the latest revision of Akaunting 2.1.14. It will be updated with different revisions or daily releases but only for Akaunting 2.1.14.

Your PR is welcome to add immutable tags mechanism along with the currently used one.

**Comment by SayakMukhopadhyay** [comment]
Correct me if I am wrong.
According to the current mechanism, if I wanted to use Akaunting 2.1.12, I would use the `2.1.12` tag from docker hub right?
If so, looking at https://hub.docker.com/layers/akaunting/akaunting/2.1.12/images/sha256-b7dd231bc50bf387820cffc3f1659d28e4e711c05542ef19672d3fdf50054792?context=explore and layer number 38, I see that the command is downloading Akaunting from the latest (as shown in the above screenshot). Doesn't this mean that if I pull the `2.1.12` image, I am still going to get `2.1.14` since that is the latest as of now?

**Comment by MohammedAl-Mahdawi** [comment]
No, if you use 2.1.12 tag you will get 2.1.12 version with its latest patch, not 2.1.14

<img width="1274" alt="Screen Shot 2021-05-28 at 12 29 51 PM" src="https://user-images.githubusercontent.com/5562839/119963331-a34fd700-bfb0-11eb-8781-4456d4b911b8.png">

The `lates` that you mentioned in layer `38` belong to akaunting.com website not even to Docker Hub, also this layer gets saved into Docker Hub at the build time and will not get downloaded again when you use(run) the image.

**Comment by SayakMukhopadhyay** [comment]
Ah! That makes sense. Thanks for explaining this to me. Much appreciated.

**Comment by MohammedAl-Mahdawi** [comment]
You are welcome!
