### ISSUE TITLE
Likely solution to 500 error on Login people are getting, suggest changing comment.

### ISSUE THREAD

**Issue by ScionOfDesign** [akaunting/docker#36]
I noticed several people were having a similar login error, and I thought I would help document the likely issue.
I personally wrestled with this issue for many, many hours. I had gotten the container to work _once_ but could not seem to get it to work after that.
It spits out unhelpful errors like:
`[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70)`
or
`[2021-05-05 20:13:09] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.asd_users' doesn't exist (SQL: select * from `asd_users` where `email` = me@company.com and `asd_users`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.asd_users' doesn't exist (SQL: select * from `asd_users` where `email` = me@company.com and `asd_users`.`deleted_at` is null limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)
`

The latter error, at least, is caused by a _mismatch_ between the environment variable `DB_HOST=akaunting-db` and the label of the database container in the `docker-compose.yml` file. (The default name is 'akaunting-db')

The _issue_ is that the environment variable DB_HOST has the following comment above it:
`# Don't change this unless you are using rootless podman, in which case you should set it to 127.0.0.1 (NOT localhost)`
This comment is inaccurate, it should state something like:
`# Don't change this unless you rename your database container or are using rootless podman, in the latter case you should set it to 127.0.0.1 (NOT localhost)`

Many people are going to want to rename their database containers, but I suspect that the 'DB_HOST' variable is being overlooked due the the 'Do not change' comment.
So yeah, if you are also having the login issue, double-check your environment variables.

**Comment by MohammedAl-Mahdawi** [comment]
Thank you for documenting your experience, agree, the comment has been updated.
