### ISSUE TITLE
Not working on RPI4

### ISSUE THREAD

**Issue by leomat** [akaunting/docker#37]
Hi,

I'm trying to install it on a Raspberry PI 4, but no success. 

When I follow your guidelines, I get this following error: 
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

I'm kinda new with all this docker process. 

Is there a way to install Akaunting on a PI? It would be amazing !

Thanks

**Comment by simonmoreau** [comment]
Hi @leomat! I managed to install Akaunting on a Raspberry Pi 4 by changing the 'mariadb' image to an image working on an arm processor:   [linuxserver/mariadb](https://github.com/simonmoreau/docker/blob/4e7da6f4a9efcc1b8a1a06072403d19e5665838f/docker-compose.yml#L25). You can find my version of the docker-compose.yml [here](https://github.com/simonmoreau/docker/blob/master/docker-compose.yml)
