### ISSUE TITLE
The "--db-prefix" option does not exist.

### ISSUE THREAD

**Issue by bstrulak** [akaunting/docker#39]
Hi,

I have a  problem running akaunting in docker environment. When I'm cloning repository, sets all the env files and then run AKAUNTING_SETUP=true docker-compose up -d I have the following error showing up:
akaunting           |   The "--db-prefix" option does not exist.

How can I solve this issue?
Thanks in advance for your help.

**Comment by loranger** [comment]
Hello

Same issue here. 
It does not work out of the box.
I tried to install manually, and then npm refused to install (node-sass seems outdated), but that's another issue…

**Comment by FaridTofighi** [comment]
> Hi,
> 
> I have a problem running akaunting in docker environment. When I'm cloning repository, sets all the env files and then run AKAUNTING_SETUP=true docker-compose up -d I have the following error showing up:
> akaunting | The "--db-prefix" option does not exist.
> 
> How can I solve this issue?
> Thanks in advance for your help.

Hello

Same here.
I built the akaunting image manually and the issue resolved.
`docker image build . akaunting:latest . --no-cache`

In docker-compose.yaml
image: akaunting:latest

**Comment by MohammedAl-Mahdawi** [comment]
Couldn't reproduce the issue using the default setup.

**Comment by aaronmweiss** [comment]
I can confirm that I too am receiving the same error, and got it to work using the instructions provided by @FaridTofighi

**Comment by MohammedAl-Mahdawi** [comment]
Please I need the steps to reproduce the issue on the default setup like:

1. Run `git clone git@github.com:akaunting/docker.git`
2. Run `cd docker`
3. Create the `.env` files.
4. Run `AKAUNTING_SETUP=true docker-compose up`
5. The issue appeared...

**Comment by loranger** [comment]
Here is a demo of the issue on a fresh setup :

[![asciicast](https://asciinema.org/a/5Jeq1Q81ADuUHByRjeZFHz9Ro.svg)](https://asciinema.org/a/5Jeq1Q81ADuUHByRjeZFHz9Ro)

I hope that could help.

(I changed the exposed port in order to avoid conflict with my running traefik dashboard instance)

**Comment by MohammedAl-Mahdawi** [comment]
Have you tried to run `docker-compose down -v` in `~/Developer/akaunting` before running `AKAUNTING_SETUP=true docker-compose up`?

**Comment by loranger** [comment]
There was no remaining akaunting on the system. 
Docker-compose had to download images, and build akaunting container.
Anyway, I flushed it again and [tried with a down -v](https://asciinema.org/a/Cl1yx5gsAhziSNH2Hs3B0gEx2)

**Comment by MohammedAl-Mahdawi** [comment]
Unfortunately not happening on my machine, I'll keep this issue open for some time and I hope someone can help you with it.

**Comment by a575606** [comment]
I'm getting this as well, and rebuilding the image hasn't solved the issue for me. I am using the default setup, with the exception that I'm already running  a mariadb container, so I removed that container from compose and added the akaunting container to the same network as the db. I've tried countless times, but the container refuses to start and the logs are filled with:

Module rewrite already enabled
  The "--db-prefix" option does not exist.  
  The "--db-prefix" option does not exist.  
  The "--db-prefix" option does not exist.  
  The "--db-prefix" option does not exist.  
  The "--db-prefix" option does not exist.  
  The "--db-prefix" option does not exist.  
Module rewrite already enabled
  The "--db-prefix" option does not exist.  


etc. 

Are there any prebuilt images available?

**Comment by a575606** [comment]
PS, not sure if this is helpful, but here's the full trace of the error from the laravel.log:

`production.ERROR: Symfony\Component\Console\Exception\RuntimeException: The "--db-prefix" option does not exist. in /var/www/html/vendor/symfony/console/Input/ArgvInput.php:223
Stack trace:
#0 /var/www/html/vendor/symfony/console/Input/ArgvInput.php(157): Symfony\Component\Console\Input\ArgvInput->addLongOption('db-prefix', 'acc_')
#1 /var/www/html/vendor/symfony/console/Input/ArgvInput.php(82): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--db-prefix=acc...')
#2 /var/www/html/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /var/www/html/vendor/symfony/console/Command/Command.php(214): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#5 /var/www/html/vendor/symfony/console/Application.php(960): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}`

**Comment by bauzhas** [comment]
I'm having same issue. Getting same error `The "--db-prefix" option does not exist.`
Container akaunting container restarts around every 30 seconds.
Trying to install the container on pi4 with arch arm distro and using linuxserver/mariadb for batabase.

Same as per a575606 comment I edited env files as per comments in the files changing usernames and passwords.
Ran `docker-compose down -v` and then `AKAUNTING_SETUP=true docker-compose up`

Unsure how to follow FaridTofighi advise to build container manually if it works. The command line provided `docker image build . akaunting:latest . --no-cache` is not  valid command.

**Comment by a575606** [comment]
@bauzhas , the command that worked for me to build manually is as follows:

`docker image build -t <name:tag for the image> -f <path to docker file> <context directory> --no-cache`

The tag can be any name and tag you choose, but you should edit the relevant docker compose file to match the name and tag. If you run the command in the docker directory you cloned from github, the context directory is '.'

i.e. to build the fpm image:
`docker image build -t akaunting-fpm:latest -f fpm.Dockerfile . --no-cache`
and then you would edit fpm-docker-compose.yml and add:
`image: akaunting-fpm:latest # not akaunting/akaunting !`

Having said that, I tried building both the default and fpm images and have yet to get either to work properly. It's quite frustrating because this looks like just the software I've been looking for for my small business, but I've yet to get it installed despite trying for 2-3 days now. I hope someone has some advice!

**Comment by joshlsullivan** [comment]
I'm having the same issue.

**Comment by MohammedAl-Mahdawi** [comment]
Since I couldn't reproduce this https://github.com/akaunting/docker/issues/39#issuecomment-851373626

If anyone want to privately share with me the access to his/her server that has the issue so I can take a deeper look it will be more than welcome.

**Comment by bauzhas** [comment]
As per https://github.com/akaunting/docker/issues/43#issuecomment-889275974 I have followed the advice.
I have tested the below on my laptop as well as raspberry pi with running linuxserver/mariadb database container for the later one - both worked fine.

I downloaded files and changed required information in as perv main README.md:
```
git clone https://github.com/akaunting/docker
cd docker
cp env/db.env.example env/db.env
vi env/db.env # and set things
cp env/run.env.example env/run.env
vi env/run.env # and set things
```
then ran as per https://github.com/akaunting/docker/issues/43#issuecomment-889275974 :
```
docker system prune -a -f
docker volume prune -f
docker network prune -f
```
this removed any unused containers and volumes

then created and started containers:
`AKAUNTING_SETUP=true docker-compose up --force-recreate -d`
