### ISSUE TITLE
README question

### ISSUE THREAD

**Issue by 1ubuntuuser** [akaunting/docker#41]
Love what you've done here. Much easier then it has been before!

Just a quick question about this line of the readme

```
After setup is complete, bring the containers down before bringing them back up without the setup variable.

docker-compose down -v
```
Are you sure you want to wipe the volumes at this point? If so, why? wont that delete all the setup done in the previous step?
```
    -v, --volumes           Remove named volumes declared in the `volumes`
                            section of the Compose file and anonymous volumes
                            attached to containers.
```

**Comment by MohammedAl-Mahdawi** [comment]
Hi, thank you for the nice words, much appreciated.
I agree, just updated the `README.md` file.
