### ISSUE TITLE
The "--db-prefix" option does not exist.

### ISSUE THREAD

**Issue by joshlsullivan** [akaunting/docker#43]
After running docker-compose up -d, I'm getting this error: "The "--db-prefix" option does not exist."

**Comment by tiktok7** [comment]
I encountered this too. it looks like the same problem is persisting: #39

**Comment by tiktok7** [comment]
I logged into the image and checked the allowed parameters. As you can see, the option really isn't included. This is what I get:

> # php artisan install --help
> Usage:
>   install [options]
> 
> Options:
>       --db-host[=DB-HOST]                Database host
>       --db-port[=DB-PORT]                Port of the database host [default: "3306"]
>       --db-name[=DB-NAME]                Name of the database
>       --db-username[=DB-USERNAME]        Username to use to access the database
>       --db-password[=DB-PASSWORD]        Password to use to access the database
>       --company-name[=COMPANY-NAME]      Name of the company managed buy the app
>       --company-email[=COMPANY-EMAIL]    email used to contact the company
>       --admin-email[=ADMIN-EMAIL]        Admin user email
>       --admin-password[=ADMIN-PASSWORD]  Admin user password
>       --locale[=LOCALE]                  Language used in the app [default: "en-GB"]
>   -h, --help                             Display this help message
>   -q, --quiet                            Do not output any message
>   -V, --version                          Display this application version
>       --ansi                             Force ANSI output
>       --no-ansi                          Disable ANSI output
>   -n, --no-interaction                   Do not ask any interactive question
>       --env[=ENV]                        The environment the command should run under
>   -v|vv|vvv, --verbose                   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
> 
> Help:
>   Allows to install Akaunting directly through CLI

Can anyone on the dev team suggest something to check? (a version or setting)

**Comment by tiktok7** [comment]
I managed to get the image working by forcing repeated rebuilds with a docker-compose build --pull / --no-cache and docker-compose up --force-recreate. (I tried a lot of different variations so I cannot be more precise). If anyone else is getting the same problem I suggest purging everything and rebuilding with similar options.

If any developers are paying attention; there is something really flaky going on with your file caches for akaunting because the files I got in the working version are definitely NOT the same as what was downloaded the first time.

**Comment by MohammedAl-Mahdawi** [comment]
Thank you for your feedback!

We already discussed this here #39

**Comment by simonmoreau** [comment]
I had the same issue and was able to run Akaunting by following @tiktok7 advice.
I started by removing all container, volumes and images (⚠ _Warning: This remove ALL images and volumes, including those not related to Akaunting_ ⚠):
```
docker stop $(docker ps -a -q) 
docker rm -v $(docker ps -a -q)
docker rmi $(docker images -a -q)
docker system prune -a -f
docker volume prune -f
docker network prune -f
```
I then run: `AKAUNTING_SETUP=true docker-compose up --force-recreate`
I was then able to run Akaunting.

**Comment by bauzhas** [comment]
> I had the same issue and was able to run Akaunting by following @tiktok7 advice.
> I started by removing all container, volumes and images (warning _Warning: This remove ALL images and volumes, including those not related to Akaunting_ warning):
> 
> ```
> docker stop $(docker ps -a -q) 
> docker rm -v $(docker ps -a -q)
> docker rmi $(docker images -a -q)
> docker system prune -a -f
> docker volume prune -f
> docker network prune -f
> ```
> 
> I then run: `AKAUNTING_SETUP=true docker-compose up --force-recreate`
> I was then able to run Akaunting.

thanks for sharing workaround. this worked for me
https://github.com/akaunting/docker/issues/39#issuecomment-900530882
