### ISSUE TITLE
docker run: can not open input file: artisan on fresh install

### ISSUE THREAD

**Issue by DiamondShark** [akaunting/docker#46]
Good morning!

Today, I tried to spin up a fresh version of the akaunting docker image, so I followed the steps on the website.

Started in a clean directory, and executed the following:

> git clone https://github.com/akaunting/docker
> cd docker
> cp env/db.env.example env/db.env
> nano env/db.env # and set things
> cp env/run.env.example env/run.env
> nano env/run.env # and set things

I changed the db password (that's the only change in db.env)
and modified run.env to include my hostname:

> You should change this to match your reverse proxy DNS name and protocol
> APP_URL=https://hostname:8080
> LOCALE=en-US
> 
> Don't change this unless you rename your database container or use rootless podman, in case of using rootless podman you should set it to 127.0.0.1 (NOT localhost)
> DB_HOST=akaunting-db
> 
> Change these to match env/db.env
> DB_DATABASE=akaunting
> DB_USERNAME=admin
> DB_PASSWORD=<matched this to db.env>
> 
> You should change this to a random string of three numbers or letters followed by an underscore
> DB_PREFIX=<264>_
> 
> These define the first company to exist on this instance. They are only used during setup.
> COMPANY_NAME=My Company
> COMPANY_EMAIL=my@company.com
> 
> This will be the first administrative user created on setup.
> ADMIN_EMAIL=me@company.com
> ADMIN_PASSWORD=password

After running any of the commands that include building the image (in the 'explore these versions of dockerized akaunting!' box), I receive the following error, after the image builds for a while:

 **Could not open input file: artisan**

The particular command in question that throws this error without fail is 

`AKAUNTING_SETUP=true docker-compose -f fpm-alpine-nginx-docker-compose.yml -f fpm-alpine-nginx-composer-supervisor-docker-compose.yml up --build`

(copied directly from the site.)

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

I couldn't reproduce the issue, probably it is related to your particular environment.

**Comment by ChristiLu** [comment]
I am having the same issue. I am using an EC2 container running Amazon Linux with the command :

``AKAUNTING_SETUP=true docker-compose -f fpm-alpine-nginx-docker-compose.yml -f fpm-alpine-nginx-composer-supervisor-docker-compose.yml up --build```

When I attach to the container, artisan is not in the directory the script runs from (```/usr/local/bin/```) and it looks like the application directory never finishes cloning the akaunting repo, so artisan isn't available to be run. 

@MohammedAl-Mahdawi could you give us more information about your environment? I would really like to use this container, but so far we have 3 different environments all failing. I understand that it works on your machine, but I'm at a loss as to why it's different on ours.
