### ISSUE TITLE
Trying to install Akuanting using docker - Portainer GUI

### ISSUE THREAD

**Issue by AAlmarwani93** [akaunting/docker#47]
I am trying to install the docker image via a portianer as a GUI mgmt for my docker instance. Below is my docker compose file:

version: '3.7'

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    networks:
      default:
        ipv4_address: 172.18.0.10
      network1:
        ipv4_address: 192.168.1.37
    volumes:
      - /volume1/docker/Akaunting/data:/var/www/html/storage
      - /volume1/docker/Akaunting/modules:/var/www/html/modules
    restart: unless-stopped
    environment:
      PUID: 1026
      PGID: 100
      TZ: Asia/Qatar
      DB_DATABASE: 'akaunting'
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'akaunting_password'
      DB_HOST: 172.18.0.11
      DB_PREFIX: asd_
      COMPANY_NAME: 'My Company'
      COMPANY_EMAIL: 'my@company.com'
      ADMIN_EMAIL: 'mycom@my.com'
      ADMIN_PASSWORD: 'password'
      APP_URL: https://example.example.com
    depends_on:
      - akaunting-db
      

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - /volume1/docker/Akaunting/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      PUID: 1026
      PGID: 100
      MYSQL_DATABASE: 'akaunting'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'akaunting_password'
      MYSQL_ROOT_PASSWORD: 'akaunting_password'
      #MYSQL_RANDOM_ROOT_PASSWORD: yes
    networks:
      default:
        ipv4_address: 172.18.0.11

networks:
  default:
    external: 
      name: ngnix_default
  network1:
    external:
      name: vlan1_macvlan_network_config

when i am logging in i can see in portainer there is an error of not finding the user. I am pretty sure that I did not put the docker compose file correctly and that is why it is getting messed up. 

Need some assistance to set this up but not sure where to start.

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

This repo is for building the official Akaunting images so please only post issues related to the official Akaunting images or the default setup of the compose files.

If you have questions or issues with your specific setup you can post your question/issue in our support channels [here](https://akaunting.com/support) or on StackOverflow.

Thank you for understanding!
