### ISSUE TITLE
Container keeps on restarting again on again

### ISSUE THREAD

**Issue by orhanerday** [akaunting/docker#52]
I got an `invalid option` error when running akaunting container. 

according to [matt ](https://stackoverflow.com/users/1318694/matt) [answer](https://stackoverflow.com/a/37473466/14373656) I run this command:

`$ docker logs --tail 50 --follow --timestamps akaunting`

output:
```
: invalid option:54.157611100Z /bin/bash: -
: invalid option:55.776651700Z /bin/bash: -
: invalid option:57.327766100Z /bin/bash: -
: invalid option:58.967840900Z /bin/bash: -
: invalid option:00.887525200Z /bin/bash: -
: invalid option:03.618328300Z /bin/bash: -
: invalid option:07.897957800Z /bin/bash: -
: invalid option:15.456709400Z /bin/bash: -
: invalid option:29.407690300Z /bin/bash: -
```

Screenshot:
![docker screenshot](https://user-images.githubusercontent.com/22305274/141731201-93010642-5d94-4f8f-90b5-d3ed82ce9f21.png)

Any idea what could be the issue here?

**Comment by orhanerday** [comment]
I deleted all related Images and Volumes problem solved.

**Comment by thond1st** [comment]
> I deleted all related Images and Volumes problem solved.

Hi @orhanerday Did you also removed watch tower and mariadb related images and volumes?
Did you repeat `AKAUNTING_SETUP=true docker-compose up -d` or just ran `docker-compose up -d` ?

Thanks

**Comment by orhanerday** [comment]
Yes, I ran just  `docker-compose up -d ` so that is the reason why?

**Comment by thond1st** [comment]
> Yes, I ran just `docker-compose up -d ` so that is the reason why?

Thank you @orhanerday

**Comment by orhanerday** [comment]
@thond1st You're welcome! I wish you good work...
