### ISSUE TITLE
Stuck at login screen

### ISSUE THREAD

**Issue by mapa17** [akaunting/docker#55]
Hello,

I am running the latest akaunting docker image using docker-compose in combination with an nginx reverse proxy mapping from

akaunting.MYDOMAIN.COM ---> akaunitng.MYDOMAIN.COM:9002

because I have multiple docker applications running don't the same host.

I can reach the login screen, but using the credentials I set in env/run.env, the login button is showing its animation but not progressing.

Any ideas whats going on, or how to debug it?
thx!

**Comment by mapa17** [comment]
I found the issue after checking the java script console of my web browser. 
Akaunting required https to be enabled int he host, and my nginx was not configured with a self signed SSL certificate in reverse proxy mode.

So the solution was to
* Create a self signed certificate
* Use the certificate and enable an SSL reverse proxy with nginx

**Comment by underthecocotree** [comment]
Things I found useful

Add a reverse proxy with caddy to use https
https://www.poorna.dev/post/Get-Started-with-Akaunting-and-Docker-with-HTTPS/

And if you are running it locally your domain will probably not be available.  Following the guid above you can also set the tls to [self signed certifciates](https://www.amitmerchant.com/local-websites-with-custom-domain-and-https-using-caddy-server/). In docker-compose you will need to map the ssl certificate and then read that on the Caddyfile.

```yml
# docker-compose.json
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/etc/caddy/ssl
```

```
# caddyfile
accounting.yourdomain.com {
    encode gzip
    reverse_proxy akaunting:80

	tls /etc/caddy/ssl/self-signed.pem /etc/caddy/ssl/self-signed-key.pem
}

```

Installation issues
https://akaunting.com/forum/discussion/installation-update/cant-run-31-with-docker?page=3
