### ISSUE TITLE
Gettng only 302 since last push when behind reverse proxy

### ISSUE THREAD

**Issue by serotonie** [akaunting/docker#56]
Hi there,

Since the last push of today, i'm only getting 302 when accessing through my Nginx Reverse Proxy.
As much as I can tell, the only thing that has changed is the Image itself, everything else is still the same.

Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.xx.x.x. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.xx.x.x. Set the 'ServerName' directive globally to suppress this message
[Sun Jan 02 17:16:51.491941 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.51 (Debian) PHP/7.4.27 configured -- resuming normal operations
[Sun Jan 02 17:16:51.492229 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.x.xx - - [02/Jan/2022:17:16:51 +0000] "GET / HTTP/1.1" 302 1642 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"

It works fine when when accessing locally (and changing APP_URL of course).

**Comment by ScionOfDesign** [comment]
I have been getting the same thing myself. I can only seem to access it locally now.

**Comment by serotonie** [comment]
Nice to not be the only one :)
I also use Nginx Proxy Manager to manage my reverse proxy and it was working flawlessly until the last sunday's push.

**Comment by ScionOfDesign** [comment]
It seems to actually be a bug in Nginx Proxy Manager: https://github.com/jc21/nginx-proxy-manager/issues/1717
The wrong port (local one instead of 443) is being passed to the akaunting app most likely.

**Comment by ScionOfDesign** [comment]
I can confirm that reverting back to Nginx Proxy Manager version 2.9.13 fixes the issue.

**Comment by serotonie** [comment]
You were just a bit faster in reverting to 2.9.13.
I can also confirm that it fixed the issue.

Thanks :)
