### ISSUE TITLE
Portainer Docker Install

### ISSUE THREAD

**Issue by jeroenmarinus** [akaunting/docker#59]
Using the Portainer GUI (a wrapper around docker-compose), it's not possible to deploy Akaunting.
The following error is thrown: Deployment Error: Couldn't find env file: /data/compose/9/env/run.env

Via the portainer GUI it's not possible to copy files, but it is possible to define several env variables (such as the ones contained in the db.env and run.env).

Could it be possible to skip the file check if the env variables are present, so deployment via Portainer becomes possible?

**Comment by cpo96** [comment]
Hey there, 

One way I got around that was to rename the db.env and run env to stack.env and use the portainer values. You can either upload or manually enter them all. However, that now means that the .env will be the same on every container. 

But I now have the issue of my docker stating it can't find the DockerFile. So I had to install by cloning and launching from cli.

**Comment by jeroenmarinus** [comment]
@cpo96 

Launching from cli works indeed, but that defeats the point of using Portainer because it leaves you with a stack in "limited" state and you lose all of portainer's management features.

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

This repo is for building the official Akaunting images so please only post issues related to the official Akaunting images or the default setup of the compose files.

If you have questions or issues with your specific setup you can post your question/issue in our support channels [here](https://akaunting.com/support) or on StackOverflow.

Thank you for understanding!

**Comment by MohammedAl-Mahdawi** [comment]
@nightred Thank you for your feedback, we have limited resources and unfortunately, we can't support every installation platform/method, we do our best to maintain and enhance this repository but please don't forget this is a community-driven repository your contribution is more than welcome, please feel free to create a pull request for the feature that you want that will help other users and make this repository better and we will be happy to accept it.
