### ISSUE TITLE
Upgrade to Akaunting 3.0

### ISSUE THREAD

**Issue by dickydick1963** [akaunting/docker#66]
After the update to Akaunting 3.0 I can't acces my companies. I think the databases are not upgraded.

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

This issue related to Akaunting software itself so I think it is better to be post on the [official repo](https://github.com/akaunting/akaunting) or using another support channel [here](https://akaunting.com/support).

Thank you for understanding!
