### ISSUE TITLE
Wizzard not loading on fresh install

### ISSUE THREAD

**Issue by piiq** [akaunting/docker#71]
Hey 👋

Just cloned the repo added localhost/127.0.0.1 to the env file

The login page loaded and verified the admin credentials but the wizzard fails on the frontend with this error
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/11668535/180600194-3e44fdfc-14ec-45f4-a1a1-1accec9bc1ce.png">

If there is something I'm missing in the installation instruction - help appreciated. If this is a bug/regression - can you advice an older version of the container (instead of `latest`) where this bug does not exist?

**Comment by davtk** [comment]
Had same issue. All you have to do is correctly set `APP_URL` in `env/run.env` (including the port)!

I gave up on it and ended up like this :))

**Comment by piiq** [comment]
@MohammedAl-Mahdawi @denisdulici I've added a PR that clarifies the documentation (#72 ) Is there anything I can do to get it merged?
