### ISSUE TITLE
issue installing 

### ISSUE THREAD

**Issue by killmasta93** [akaunting/docker#78]
hi @MohammedAl-Mahdawi 
Currently using this guide https://developer.akaunting.com/documentation/install-via-docker/
but im getting this error but only happens when i run docker compose down then up again because in the initial installation it works 

`Access denied for user 'admin'@'%' to database 'forge' akaunting`

using the default settings 

Thank you

**Comment by Scarpall** [comment]
Hey there, i got the same problem. seems to be from the container. i just used the v-docker-compose.yml & v.Dockerfile and then everything works even after setup

**Comment by killmasta93** [comment]
thank you so much @Scarpall  that did the trick but not sure when create users i keep getting oops something went wrong

not sure if you got the same issue

**Comment by Scarpall** [comment]
@killmasta93 hey i just checked it. you need to configure an mail server under: Settings --> Email
after i added my smtp settings everything worked fine.

I didnt found a way to manually add an account.

**Comment by killmasta93** [comment]
thank you so much that did the trick
