### ISSUE TITLE
:latest 3.0.16 not working

### ISSUE THREAD

**Issue by vitis586** [akaunting/docker#95]
Hi,
My testing container only works locally, is not exposed to internet and uses `:latest` tag. My production is exposed to the internet and uses `:3` tag. Everything was working fine up until today.
I filled my production container with some data yesterday evening. I went through the data see all of it. Today both of containers are showing the error in the browser. The docker tags got updated yesterday so I guess it has to be something connected with this.

Logs for the container do not show anything useful. There are HTTP 200s on every access but I still see only the error below.

> 
> Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1159
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1170
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1182
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1195
> 
> Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788
> 
> Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 862
> 
> Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788
> 
> Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 862
> 
> Deprecated: Return type of Illuminate\Routing\RouteCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php on line 343
> 
> Deprecated: Return type of Illuminate\Routing\RouteCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php on line 333
> 
> Deprecated: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 552
> 
> Deprecated: Return type of Illuminate\Http\Request::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 563
> 
> Deprecated: Return type of Illuminate\Http\Request::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 575
> 
> Deprecated: Return type of Illuminate\Http\Request::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 586
> 
> Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/ParameterBag.php on line 220
> 
> Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/ParameterBag.php on line 230
> 
> Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/HeaderBag.php on line 280
> 
> Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/HeaderBag.php on line 290
> 
> Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/symfony/http-foundation/Request.php on line 316
> 
> Deprecated: mb_strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 94
> 
> Deprecated: mb_strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 94
> 
> Deprecated: auto_detect_line_endings is deprecated in /var/www/html/vendor/vlucas/phpdotenv/src/Loader.php on line 167
> 
> Deprecated: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 116
> 
> Deprecated: Return type of Illuminate\Config\Repository::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 127
> 
> Deprecated: Return type of Illuminate\Config\Repository::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 139
> 
> Deprecated: Return type of Illuminate\Config\Repository::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 150
> 
> Deprecated: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Finder.php on line 565
> 
> Deprecated: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Finder.php on line 636
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FilterIterator.php on line 32
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php on line 42
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 85
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 113
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 65
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 55
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 71
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FilterIterator.php on line 32
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FilenameFilterIterator.php on line 28
> 
> Deprecated: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/PathFilterIterator.php on line 27
> 
> Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1300
> 
> Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1311
> 
> Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1323
> 
> Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1334
> 
> Deprecated: Return type of Illuminate\Database\Eloquent\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 927
>

**Comment by raenrfm** [comment]
Having the exact same issue with my docker container.  Web page displaying these Depricated errors.  Here are mine in case there are any differences:


Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1159

Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1170

Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1182

Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1195

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 862

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 862

Deprecated: Return type of Illuminate\Routing\RouteCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php on line 343

Deprecated: Return type of Illuminate\Routing\RouteCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php on line 333

Deprecated: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 552

Deprecated: Return type of Illuminate\Http\Request::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 563

Deprecated: Return type of Illuminate\Http\Request::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 575

Deprecated: Return type of Illuminate\Http\Request::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 586

Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/ParameterBag.php on line 220

Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/ParameterBag.php on line 230

Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/HeaderBag.php on line 280

Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/http-foundation/HeaderBag.php on line 290

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/symfony/http-foundation/Request.php on line 316

Deprecated: mb_strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 94

Deprecated: mb_strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 94

Deprecated: auto_detect_line_endings is deprecated in /var/www/html/vendor/vlucas/phpdotenv/src/Loader.php on line 167

Deprecated: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 116

Deprecated: Return type of Illuminate\Config\Repository::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 127

Deprecated: Return type of Illuminate\Config\Repository::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 139

Deprecated: Return type of Illuminate\Config\Repository::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 150

Deprecated: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Finder.php on line 565

Deprecated: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Finder.php on line 636

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FilterIterator.php on line 32

Deprecated: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php on line 42

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 85

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 113

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 65

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 55

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 71

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FilterIterator.php on line 32

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/FilenameFilterIterator.php on line 28

Deprecated: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/symfony/finder/Iterator/PathFilterIterator.php on line 27

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1300

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1311

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1323

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1334

Deprecated: Return type of Illuminate\Database\Eloquent\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 927

**Comment by vitis586** [comment]
I just tried wiping my testing instance and starting over. Still not working the only difference being that the errors end up in the container logs.

The docker container got an update during today but that one is still not working.

**Comment by raenrfm** [comment]
I just went back to 3.0.15 and it's good again.  Just going to wait until
they figure out what's wrong with it.

**Comment by raenrfm** [comment]
Spoke too soon I guess the database got upgraded and rolling back means I
can't create any invoices or bills etc.

**Comment by raenrfm** [comment]
Noticed that the latest image was updated 2 hours ago but still no
go...getting the deprication errors.  I really hope this gets resolved
soon, I'm dead in the water because when it upgraded it also updated the
database and now I can't roll back.

**Comment by vitis586** [comment]
I also tried most of the new builds but without luck. It is strange that the image gets updated but it is still 3.0.16. Seems like that some of the accompanying packages are getting updates.

I am using only the transactions part so far and that is working.

**Comment by raenrfm** [comment]
I managed to get it working by rolling back to 3.0.13. Haven't tried moving
beyond but might test each version to see.

**Comment by vitis586** [comment]
I managed to start the test container with the new 3.0.17 via the `:latest` tag. The `:latest` is currently the same as `3.0.17` tag but there is also `3.0.17-v` with different digest. There are small difference in the dockerfiles. I am not sure if the tag will be getting the updates in the same manor (changing digest while keeping the same tag) or something chnaged. I will not go with `:latest` but I will monitor how the updates affect the two 3.0.17 tags a choose one of those probably.
Nor the `3.0.16-v` neither the `3.0.16` are working for me. I have not tried the fpm or alpine versions. I never got those running. They have exposed different port and are not aligned with the documentation.
I will also have a look into Bigcapital as I am not heavily invested in Akaunting yet.

**Comment by vitis586** [comment]
@raenrfm Just to let you know what I sorted out. I am using the latest 3.0.17 but both the `3.0.17` and `3.0.17-v` tags are still changing. I resorted to using the digest as my tag, so I am using tag `akaunting/akaunting@sha256:f35f4f77927945a3b7618675d7129be30cd15170e81cfbbc77280651b32affca`. This gives me the latest version but does not get change every now and then. It is locked to the current state of the tag so automatic updates wont work unfortunately.

**Comment by raenrfm** [comment]
Ah great work, it's also working for me now, thank you!

**Comment by raenrfm** [comment]
So my wife decided to run updates inside our installation and now it's
messed up it probably updated something in the database and if I try to
recreate the container with the old image I'm getting this now:

components.layouts.error.head
components.layouts.error.content
components.layouts.error.scripts

and nothing else.  I tried the latest image and it goes through setup but
never connects to my mariadb...it's stuck on step 2...any ideas?

**Comment by vitis586** [comment]
Hi @raenrfm, there has not been any database migration since the 3.1.0 so the database should be fine. I would back up the database and try to update the image. I use or used these tags:
- 3.1.3 
  - akaunting/akaunting@sha256:4ce452965ca29c8b879982ff50cc600d6775d504d7f4786a7126005705226bf2
- 3.1.4 
  - akaunting/akaunting@sha256:b41f354b7cbd583a25795df26886c6310cd80140d830a257e4b2df48c03f7cbb
- 3.1.5 
  - akaunting/akaunting@sha256:70cfb20bfea7ab104b229f27f4555f5b91f7978d789262221b4345b046ead732

For future I suggest using automated database backup. I use this https://hub.docker.com/r/tiredofit/db-backup/

Is the failing installation maybe failing because of the latest changes, that detect if the service is already installed? I also noticed that while changing to 3.1.5. See more and potential fix for you in - https://github.com/akaunting/docker/issues/107

**Comment by danietech** [comment]
Hi

I have been following this issue and after extensive testing I have not been able to use as normal, below is the log from my UNRAID docker instance.

----------------------
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
❌ Some options are missing and --no-interaction is present. Please run the following command for more information :
❌ php artisan help install
❌ Missing options are : db-port, db-name
❌ Some options are missing and --no-interaction is present. Please run the following command for more information :
❌ php artisan help install
❌ Missing options are : db-port, db-name
❌ Some options are missing and --no-interaction is present. Please run the following command for more information :
❌ php artisan help install
❌ Missing options are : db-port, db-name
---------------------------

- I have rolled back incrementally from 3.0 / 3.1.7 
- Added Variable DB...Etc  "DB_NAME/DB_PREFIX/DB_PORT"

-----------------------------
#  php artisan help install
Description:
  Allows to install Akaunting directly through CLI

Usage:
  install [options]

Options:
      --db-host[=DB-HOST]                Database host [default: "localhost"]
      --db-port[=DB-PORT]                Port of the database host [default: "3306"]
      --db-name[=DB-NAME]                Name of the database
      --db-username[=DB-USERNAME]        Username to use to access the database [default: "root"]
      --db-password[=DB-PASSWORD]        Password to use to access the database
      --db-prefix[=DB-PREFIX]            Table name prefix
      --company-name[=COMPANY-NAME]      Name of the company [default: "My Company"]
      --company-email[=COMPANY-EMAIL]    Email of the company [default: "my@company.com"]
      --admin-email[=ADMIN-EMAIL]        Admin user email
      --admin-password[=ADMIN-PASSWORD]  Admin user password
      --locale[=LOCALE]                  Language used in the app [default: "en-GB"]
  -h, --help                             Display help for the given command. When no command is given display help for the list command
  -q, --quiet                            Do not output any message
  -V, --version                          Display this application version
      --ansi|--no-ansi                   Force (or disable --no-ansi) ANSI output
  -n, --no-interaction                   Do not ask any interactive question
      --env[=ENV]                        The environment the command should run under
  -v|vv|vvv, --verbose                   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
# 
-----------------------------------

Just to be clear I had full functionality when I was using at the back end of last year, I did get a number of constant updates, since It's my company year end, I need to use this software unfortunately now it broken, any help would be much appreciated.

Disclaimer I am not a programmer or dev ops, however I can be guided if I have miss any information that may be relevant to this issue, in short I would be glad to help

Regards
Danietech
