### ISSUE TITLE
Has this docker project died?

### ISSUE THREAD

**Issue by NajibNour** [akaunting/docker#96]
Good day, 
Hope all is well. Ive had multiple issues in regards to getting this instance up and running.

### Could not open input file: artisan

When starting off with the instructions given within the readme the first issue encountered is **"Could not open input file: artisan"** 
Looking back at the history of the docker compose files, the volume for akauntung-data pointed to /var/www/html/storage and not /var/www/html.

I made that change and we were up and running... for now.

I had bring up the containers using the "AKAUNTING_SETUP=true" variable and went trough the setup process.

Once done I bring down the containers and bring them back up.

### Access denied for user 'admin'@'%' to database 'forge'

This brings us to our second issue. I said no problem instead of haggling with it for the forge DB let me just give it root and see if that works.
Gave it the root user and password for the db and the error seemed to have disappeared. But I cannot seem to login. 

Hmmm let's turn on Debug and see what's going on here.

### APP_DEBUG=true
This didn't seem to do anything I think it only activates after I login. 
However I did look into the network tab within the chrome dev tools and found this.

"SQLSTATE[HY000] [1049] Unknown database 'forge' (Connection: mysql, SQL: select * from `asd_users` where `email` = me@company.ca and `asd_users`.`deleted_at` is null limit 1)"

wow its complaining about the forge database again.

I decide to clear the artisan cache and try again (php artisan cache:clear)
Hmm same error. 

This is where im stuck. Im not sure how to proceed from here.

Would any of the developers be able to help out by chance? @MohammedAl-Mahdawi 

We really do love akaunting and really want to keep using it!

**Comment by vitis586** [comment]
It is not dead, but not frequently maintained. The issue here is that the target database environment variable has different name when `AKAUNTING_SETUP=true` and when `AKAUNTING_SETUP=false`. If you specify it with `DB_DATABASE` and `DB_NAME`, you will have it working in both settings. More information here - https://github.com/akaunting/docker/issues/85#issuecomment-1427158960

**Comment by NajibNour** [comment]
I can confirm that this does indeed fix my issue. Will submit a PR.

**Comment by chendelin1982** [comment]
Yes, I also used DB_DATABASE, it can running, but DB_NAME is bad
